### ISSUE TITLE
Revamp Google Chrome & Firefox Extension

### ISSUE THREAD

**Issue by tanmoysrt** [CircuitVerse/CircuitVerse-Presentation-Embed#30]
**Introduction**
Revamp the google chrome extension.
We can remove its dependency over google slides add-on(which is not available). By using google apis for slide and token based oauth 2.0.
By this we can make that user friendly.

**Tasks list**

- [x] UI Design [Design Here](https://www.figma.com/file/I6qAJbSV4W69NNWZbNdcr7/Circuitverse-Forum-UI?node-id=0%3A1&t=c6tDBVeCvzyivXR5-0)  
- [x] Convert to manifest v3. As support of manifest v2 going to removed in 2023
- [x] OAuth 2.0 Implicit Token Based Authorization
- [x] Implementation of  API for Insert Image and add hyperlink to it
- [x] UI Implement 
- [x] Integrate UI

**Are you working on this issue ?**
Yes

**Comment by Nitishupkr** [comment]
Can u please assign me this issue i can resolve this issue

**Comment by tanmoysrt** [comment]
> Can u please assign me this issue i can resolve this issue

It's already resolved. I have created PR ans waiting for the reply. If you want to more on that, you can check that out obviously
